<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Hiragana;

class HiraganaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hiragana = [
            ["hiragana"=>"あ","romanji"=>"a"],
            ["hiragana"=>"い","romanji"=>"i"],
            ["hiragana"=>"う","romanji"=>"u"],
            ["hiragana"=>"え","romanji"=>"e"],
            ["hiragana"=>"お","romanji"=>"o"],
            ["hiragana"=>"か","romanji"=>"ka"],
            ["hiragana"=>"き","romanji"=>"ki"],
            ["hiragana"=>"く","romanji"=>"ku"],
            ["hiragana"=>"け","romanji"=>"ke"],
            ["hiragana"=>"こ","romanji"=>"ko"],
            ["hiragana"=>"さ","romanji"=>"sa"],
            ["hiragana"=>"し","romanji"=>"shi"],
            ["hiragana"=>"す","romanji"=>"su"],
            ["hiragana"=>"せ","romanji"=>"se"],
            ["hiragana"=>"そ","romanji"=>"so"],
            ["hiragana"=>"た","romanji"=>"ta"],
            ["hiragana"=>"ち","romanji"=>"chi"],
            ["hiragana"=>"つ","romanji"=>"stu"],
            ["hiragana"=>"て","romanji"=>"te"],
            ["hiragana"=>"と","romanji"=>"to"],
            ["hiragana"=>"な","romanji"=>"na"],
            ["hiragana"=>"に","romanji"=>"ni"],
            ["hiragana"=>"ぬ","romanji"=>"nu"],
            ["hiragana"=>"ね","romanji"=>"ne"],
            ["hiragana"=>"の","romanji"=>"no"],
            ["hiragana"=>"は","romanji"=>"ha"],
            ["hiragana"=>"ひ","romanji"=>"hi"],
            ["hiragana"=>"ふ","romanji"=>"fu"],
            ["hiragana"=>"へ","romanji"=>"he"],
            ["hiragana"=>"ほ","romanji"=>"ho"],
            ["hiragana"=>"ま","romanji"=>"ma"],
            ["hiragana"=>"み","romanji"=>"mi"],
            ["hiragana"=>"む","romanji"=>"mu"],
            ["hiragana"=>"め","romanji"=>"me"],
            ["hiragana"=>"も","romanji"=>"mo"],
            ["hiragana"=>"や","romanji"=>"ya"],
            ["hiragana"=>"ゆ","romanji"=>"yu"],
            ["hiragana"=>"よ","romanji"=>"yo"],
            ["hiragana"=>"ら","romanji"=>"ra"],
            ["hiragana"=>"り","romanji"=>"ri"],
            ["hiragana"=>"る","romanji"=>"ru"],
            ["hiragana"=>"れ","romanji"=>"re"],
            ["hiragana"=>"ろ","romanji"=>"ro"],
            ["hiragana"=>"わ","romanji"=>"wa"],
            ["hiragana"=>"を","romanji"=>"o"],
            ["hiragana"=>"ん","romanji"=>"n"],
            ["hiragana"=>"が","romanji"=>"ga"],
            ["hiragana"=>"ぎ","romanji"=>"gi"],
            ["hiragana"=>"ぐ","romanji"=>"gu"],
            ["hiragana"=>"げ","romanji"=>"ge"],
            ["hiragana"=>"ご","romanji"=>"go"],
            ["hiragana"=>"ざ","romanji"=>"za"],
            ["hiragana"=>"じ","romanji"=>"ji"],
            ["hiragana"=>"ず","romanji"=>"zu"],
            ["hiragana"=>"ぜ","romanji"=>"ze"],
            ["hiragana"=>"ぞ","romanji"=>"zo"],
            ["hiragana"=>"だ","romanji"=>"da"],
            ["hiragana"=>"ぢ","romanji"=>"ji"],
            ["hiragana"=>"づ","romanji"=>"zu"],
            ["hiragana"=>"で","romanji"=>"de"],
            ["hiragana"=>"ど","romanji"=>"do"],
            ["hiragana"=>"ば","romanji"=>"ba"],
            ["hiragana"=>"び","romanji"=>"bi"],
            ["hiragana"=>"ぶ","romanji"=>"bu"],
            ["hiragana"=>"べ","romanji"=>"be"],
            ["hiragana"=>"ぼ","romanji"=>"bo"],
            ["hiragana"=>"ぱ","romanji"=>"pa"],
            ["hiragana"=>"ぴ","romanji"=>"pi"],
            ["hiragana"=>"ぷ","romanji"=>"pu"],
            ["hiragana"=>"ぺ","romanji"=>"pe"],
            ["hiragana"=>"ぽ","romanji"=>"po"],
            ["hiragana"=>"きゃ","romanji"=>"kya"],
            ["hiragana"=>"きゅ","romanji"=>"kyu"],
            ["hiragana"=>"きょ","romanji"=>"kyo"],
            ["hiragana"=>"しゃ","romanji"=>"sha"],
            ["hiragana"=>"しゅ","romanji"=>"shi"],
            ["hiragana"=>"しょ","romanji"=>"shu"],
            ["hiragana"=>"ちゃ","romanji"=>"cha"],
            ["hiragana"=>"ちゅ","romanji"=>"chi"],
            ["hiragana"=>"ちょ","romanji"=>"chu"],
            ["hiragana"=>"にゃ","romanji"=>"nya"],
            ["hiragana"=>"にゅ","romanji"=>"nyu"],
            ["hiragana"=>"にょ","romanji"=>"nyo"],
            ["hiragana"=>"ひゃ","romanji"=>"hya"],
            ["hiragana"=>"ひゅ","romanji"=>"hyu"],
            ["hiragana"=>"ひょ","romanji"=>"hyo"],
            ["hiragana"=>"みゃ","romanji"=>"mya"],
            ["hiragana"=>"みゅ","romanji"=>"myu"],
            ["hiragana"=>"みょ","romanji"=>"myo"],
            ["hiragana"=>"りゃ","romanji"=>"rya"],
            ["hiragana"=>"りゅ","romanji"=>"ryu"],
            ["hiragana"=>"りょ","romanji"=>"ryo"],
            ["hiragana"=>"ぎゃ","romanji"=>"gya"],
            ["hiragana"=>"ぎゅ","romanji"=>"gyu"],
            ["hiragana"=>"ぎょ","romanji"=>"gyo"],
            ["hiragana"=>"じゃ","romanji"=>"ja"],
            ["hiragana"=>"じゅ","romanji"=>"ju"],
            ["hiragana"=>"じょ","romanji"=>"jo"],
            ["hiragana"=>"びゃ","romanji"=>"bya"],
            ["hiragana"=>"にゅ","romanji"=>"byu"],
            ["hiragana"=>"にょ","romanji"=>"byo"],
            ["hiragana"=>"ぴゃ","romanji"=>"pya"],
            ["hiragana"=>"ぴゅ","romanji"=>"pyu"],
            ["hiragana"=>"ぴょ","romanji"=>"pyo"],
        ];
        foreach($hiragana as $word){
            Hiragana::create($word);
        }
    }
}
